language: node_js
node_js:
    - 0.12
before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
before_install:
    - gem update --system
    - gem install sass
    - npm install -g gulp
script: "gulp test:ci"
